### ISSUE TITLE
Cannot find module 'core-util-is' after running gulp and bower install

### ISSUE THREAD

**Issue by amite** [jgoux/generator-angulpify#3]
When I run `gulp` I get this error:

```
   Cannot find module 'core-util-is'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/amiterandole/Documents/current/webdev/angulpify/node_modules/gulp-if/node_modules/through2/node_modules/readable-stream/lib/_stream_duplex.js:39:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by ANiedritis** [comment]
"Then you can look at the dependencies inside the package.jsonfile and try to install them one by one, for example : npm install yargs."

Yep, got the same error because of my impatience, and this did fix this error.

**Comment by mnpenner** [comment]
I just hit this error. Try nuking your `node_modules` directory and re-installing (`npm install`).

**Comment by Dynom** [comment]
I had this error too. I ran a npm install in a docker container. This probably has no relation but it's a pain to sort everything out when you have a gazillion (recursive) npm packages.

**Comment by andrewluetgers** [comment]
had same problem after nuking project node_modules. A clean install after to require nuking both the project and global node_modules folders did the trick.

**Comment by kdcllc** [comment]
I used VS.NET 2015 and my project experienced this problem so I deleted npm cache that is specific to the project and was able to user Task Runner Explore (TRE) within the project. Visual Studio.NET 2015 by default downloads all of the dependencies when TRE is open.
